In [3]:
import pandas as pd
import numpy as np

In [4]:
data_protein = pd.read_csv('tabla_original_protein.groups.tsv', sep='\t', index_col=0)

In [5]:
data_protein

,C:\DIA-NN\AOESB2025\THF-2-01.mzML,C:\DIA-NN\AOESB2025\THF-2-02.mzML,C:\DIA-NN\AOESB2025\THF-2-03.mzML,C:\DIA-NN\AOESB2025\THF-2-04.mzML,C:\DIA-NN\AOESB2025\THF-2-05.mzML,C:\DIA-NN\AOESB2025\THF-2-06.mzML,C:\DIA-NN\AOESB2025\THF-2-07.mzML,C:\DIA-NN\AOESB2025\THF-2-08.mzML,C:\DIA-NN\AOESB2025\THF-2-09.mzML,C:\DIA-NN\AOESB2025\THF-2-10.mzML,...,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-03.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-04.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-05.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-06.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-07.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-08.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-09.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-10.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-11.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-12.mzML
Protein.Group,,,,,,,,,,,,,,,,,,,,,
O07451,8.811785e+07,8.377591e+07,8.549535e+07,NaN,3.305377e+06,NaN,NaN,2.411733e+06,NaN,NaN,...,33,0,4,0,0,4,0,0,0,0
O30338,2.932314e+06,3.109371e+06,3.269720e+06,3.246691e+06,2.865869e+06,2.605574e+06,2.899065e+06,2.941935e+06,2.931496e+06,4.518194e+06,...,3,3,3,3,3,3,3,3,3,3
O34162,2.904520e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.908280e+06,...,0,0,0,0,0,0,0,1,0,0
O87816,1.554179e+08,1.447286e+08,1.564118e+08,2.317830e+08,2.523855e+08,2.351831e+08,1.897489e+08,1.942599e+08,1.990659e+08,NaN,...,12,13,15,14,12,14,12,0,0,0
P14611,6.596207e+09,5.718506e+09,5.286449e+09,7.730208e+09,6.363529e+09,7.163563e+09,8.550903e+09,7.545575e+09,8.137098e+09,3.070406e+09,...,69,64,67,65,68,69,69,60,59,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q8KLU8,7.982015e+06,7.708948e+06,6.491463e+06,1.082711e+07,1.098730e+07,1.231335e+07,9.429833e+06,8.652352e+06,9.122981e+06,6.124467e+06,...,5,5,6,5,5,6,5,5,5,3
Q9K4U8,2.558530e+06,2.391630e+06,1.933630e+06,NaN,1.604460e+06,NaN,NaN,NaN,2.219030e+06,3.304990e+06,...,1,0,1,0,0,0,1,1,0,0
Q9K4V0,2.735580e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.443670e+06,...,0,0,0,0,0,0,0,1,1,0
Q9X6U2,6.044970e+08,5.611470e+08,5.083021e+08,7.783023e+08,6.803455e+08,7.659636e+08,8.398934e+08,7.503122e+08,8.229042e+08,3.928699e+08,...,22,21,21,22,22,22,21,22,21,22
Q9ZHI5,1.747108e+09,1.314917e+09,1.161654e+09,1.397097e+09,1.048555e+09,1.427757e+09,1.447534e+09,1.099775e+09,1.245113e+09,1.325252e+09,...,16,13,15,15,16,16,15,17,16,15

In [ ]:
#Columnas importantes para el trabajo
columns_seleccionadas = ['C:\DIA-NN\AOESB2025\THF-2-01.mzML',
                         'C:\DIA-NN\AOESB2025\THF-2-02.mzML',
                         'C:\DIA-NN\AOESB2025\THF-2-03.mzML',
                         'C:\DIA-NN\AOESB2025\THF-2-07.mzML', 
                         'C:\DIA-NN\AOESB2025\THF-2-08.mzML',
                         'C:\DIA-NN\AOESB2025\THF-2-09.mzML',
                         'UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-01.mzML',
                         'UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-02.mzML',
                         'UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-03.mzML',
                         'UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-07.mzML',
                         'UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-08.mzML',
                         'UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-09.mzML',
                         ]

In [7]:
#Filtro columnas importantes
data_protein = data_protein[columns_seleccionadas]

In [8]:
data_protein

,C:\DIA-NN\AOESB2025\THF-2-01.mzML,C:\DIA-NN\AOESB2025\THF-2-02.mzML,C:\DIA-NN\AOESB2025\THF-2-03.mzML,C:\DIA-NN\AOESB2025\THF-2-07.mzML,C:\DIA-NN\AOESB2025\THF-2-08.mzML,C:\DIA-NN\AOESB2025\THF-2-09.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-01.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-02.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-03.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-07.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-08.mzML,UniquePeptides_C:\DIA-NN\AOESB2025\THF-2-09.mzML
Protein.Group,,,,,,,,,,,,
O07451,8.811785e+07,8.377591e+07,8.549535e+07,NaN,2.411733e+06,NaN,29,34,33,0,4,0
O30338,2.932314e+06,3.109371e+06,3.269720e+06,2.899065e+06,2.941935e+06,2.931496e+06,3,3,3,3,3,3
O34162,2.904520e+06,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0
O87816,1.554179e+08,1.447286e+08,1.564118e+08,1.897489e+08,1.942599e+08,1.990659e+08,12,9,12,12,14,12
P14611,6.596207e+09,5.718506e+09,5.286449e+09,8.550903e+09,7.545575e+09,8.137098e+09,68,66,69,68,69,69
...,...,...,...,...,...,...,...,...,...,...,...,...
Q8KLU8,7.982015e+06,7.708948e+06,6.491463e+06,9.429833e+06,8.652352e+06,9.122981e+06,5,5,5,5,6,5
Q9K4U8,2.558530e+06,2.391630e+06,1.933630e+06,NaN,NaN,2.219030e+06,1,1,1,0,0,1
Q9K4V0,2.735580e+06,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0
Q9X6U2,6.044970e+08,5.611470e+08,5.083021e+08,8.398934e+08,7.503122e+08,8.229042e+08,21,22,22,22,22,21
Q9ZHI5,1.747108e+09,1.314917e+09,1.161654e+09,1.447534e+09,1.099775e+09,1.245113e+09,17,16,16,16,16,15

In [5]:
#Renombro esas columnas con nombres más simples
remplazo_columnas = ['CBB_01', 'CBB_02', 'CBB_03',
                     'rGlyP_07', 'rGlyP_08','rGlyP_09',
                     'CBB_UP_01','CBB_UP_02','CBB_UP_03',
                     'rGlyP_UP_07', 'rGlyP_UP_08','rGlyP_UP_09']

main_columns = ['CBB_01', 'CBB_02', 'CBB_03','rGlyP_07', 'rGlyP_08','rGlyP_09',]
num_columns = ['CBB_UP_01', 'CBB_UP_02', 'CBB_UP_03', 'rGlyP_UP_07', 'rGlyP_UP_08', 'rGlyP_UP_09']

data_protein.columns = remplazo_columnas

In [6]:
data_protein

,CBB_01,CBB_02,CBB_03,rGlyP_07,rGlyP_08,rGlyP_09,CBB_UP_01,CBB_UP_02,CBB_UP_03,rGlyP_UP_07,rGlyP_UP_08,rGlyP_UP_09
Protein.Group,,,,,,,,,,,,
O07451,8.811785e+07,8.377591e+07,8.549535e+07,NaN,2.411733e+06,NaN,29,34,33,0,4,0
O30338,2.932314e+06,3.109371e+06,3.269720e+06,2.899065e+06,2.941935e+06,2.931496e+06,3,3,3,3,3,3
O34162,2.904520e+06,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0
O87816,1.554179e+08,1.447286e+08,1.564118e+08,1.897489e+08,1.942599e+08,1.990659e+08,12,9,12,12,14,12
P14611,6.596207e+09,5.718506e+09,5.286449e+09,8.550903e+09,7.545575e+09,8.137098e+09,68,66,69,68,69,69
...,...,...,...,...,...,...,...,...,...,...,...,...
Q8KLU8,7.982015e+06,7.708948e+06,6.491463e+06,9.429833e+06,8.652352e+06,9.122981e+06,5,5,5,5,6,5
Q9K4U8,2.558530e+06,2.391630e+06,1.933630e+06,NaN,NaN,2.219030e+06,1,1,1,0,0,1
Q9K4V0,2.735580e+06,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0
Q9X6U2,6.044970e+08,5.611470e+08,5.083021e+08,8.398934e+08,7.503122e+08,8.229042e+08,21,22,22,22,22,21
Q9ZHI5,1.747108e+09,1.314917e+09,1.161654e+09,1.447534e+09,1.099775e+09,1.245113e+09,17,16,16,16,16,15

In [7]:
#Aplico el log2(x) pero solo de las columnas main
data_protein[main_columns] = np.log2(data_protein[main_columns])

In [8]:
data_protein

,CBB_01,CBB_02,CBB_03,rGlyP_07,rGlyP_08,rGlyP_09,CBB_UP_01,CBB_UP_02,CBB_UP_03,rGlyP_UP_07,rGlyP_UP_08,rGlyP_UP_09
Protein.Group,,,,,,,,,,,,
O07451,26.392931,26.320032,26.349343,NaN,21.201639,NaN,29,34,33,0,4,0
O30338,21.483608,21.568191,21.640735,21.467156,21.488334,21.483205,3,3,3,3,3,3
O34162,21.469868,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0
O87816,27.211578,27.108774,27.220774,27.499516,27.533413,27.568671,12,9,12,12,14,12
P14611,32.618989,32.412991,32.299652,32.993430,32.812984,32.921867,68,66,69,68,69,69
...,...,...,...,...,...,...,...,...,...,...,...,...
Q8KLU8,22.928322,22.878103,22.630112,23.168801,23.044661,23.121074,5,5,5,5,6,5
Q9K4U8,21.286884,21.189563,20.882880,NaN,NaN,21.081498,1,1,1,0,0,1
Q9K4V0,21.383415,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0
Q9X6U2,29.171160,29.063804,28.921111,29.645631,29.482916,29.616149,21,22,22,22,22,21
Q9ZHI5,30.702322,30.292324,30.113533,30.430950,30.034561,30.213630,17,16,16,16,16,15

In [9]:
data_protein.to_csv('00_prepro_protein.groups.tsv', sep='\t')